# Create a deploy with run workflow button
name: Deploy
  on:
    workflow_dispatch:
  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build and test
          run: |
            echo "Build and Test"

        - name: Deploy to production
          run: |
            echo "Deploy to production"